name: Deploy on PR

on: pull_request

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROFILESOUP }}"
          projectId: profilesoup
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
